language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential apache2-prefork-dev libhiredis-dev libhiredis0.10 libgeoip-dev apache2 check
script: ./autogen.sh && ./configure && make && make check && script/bootstrap
compiler:
  - clang
  - gcc
services:
  - redis-server