language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential apache2-prefork-dev libhiredis-dev libhiredis0.10 libgeoip-dev
script: make install_local && bundle install && rake
compiler:
  - clang
  - gcc